apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  #namespace: dev-dexter
  labels:
    app: dexter #reviews
    version: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dexter #reviews
      version: 
  template:
    metadata:
      labels:
        app: dexter #reviews
        version: 
    spec:
      serviceAccountName: dexter-service #bookinfo-reviews
      containers:
      - name: dexter #reviews
        image: 
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 80 #9080
