apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-v2
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
  #metrics:
          #- type: Resource
          #resource:
          #name: cpu
          #target:
          #type: Utilization
          #averageUtilization: 20
          # - type: Resource
          #resource:
          #name: memory
          #targetAverageUtilization: 30
