apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
    app.kubernetes.io/managed-by: Helm
  name: myweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: LoadBalancer
status:
  loadBalancer: {}
